const decks = {
    set1: [
        { question: "Which river is known as the National River of India?", answer: "Ganga" },
        { question: "Who is known as the Missile Man of India?", answer: "Dr. A.P.J. Abdul Kalam" },
        { question: "What is the national heritage animal of India?", answer: "Elephant" },
        { question: "Which city is known as the Electronic City of India?", answer: "Bengaluru" },
        { question: "In which year did India win its first Cricket World Cup?", answer: "1983" },
        { question: "What is the capital city of India?", answer: "New Delhi" },
        { question: "Which state is known as the 'Spice Garden of India'?", answer: "Kerala" },
        { question: "What is the national currency of India?", answer: "Indian Rupee" },
        { question: "Which is the largest state in India by area?", answer: "Rajasthan" },
        { question: "Which is the most populous state in India?", answer: "Uttar Pradesh" },
        { question: "Who was the first Prime Minister of India?", answer: "Jawaharlal Nehru" },
        { question: "Who was the first President of India?", answer: "Dr. Rajendra Prasad" },
        { question: "Which historical monument was built by Shah Jahan in memory of his wife?", answer: "Taj Mahal" },
        { question: "What is the national bird of India?", answer: "Indian Peacock" },
        { question: "What is the national animal of India?", answer: "Bengal Tiger" },
        { question: "What is the national flower of India?", answer: "Lotus" },
        { question: "Which Indian festival is known as the 'Festival of Lights'?", answer: "Diwali" },
        { question: "Which festival celebrates the victory of colors and spring?", answer: "Holi" },
        { question: "Who wrote the national anthem of India, 'Jana Gana Mana'?", answer: "Rabindranath Tagore" },
        { question: "Who wrote the national song of India, 'Vande Mataram'?", answer: "Bankim Chandra Chatterjee" },
        { question: "Which is the highest mountain peak located entirely within India?", answer: "Kanchenjunga" },
        { question: "Which classic Indian text is considered the oldest scripture?", answer: "Rigveda" },
        { question: "Which state has the longest coastline in India?", answer: "Gujarat" },
        { question: "What is the name of India's space research organization?", answer: "ISRO" },
        { question: "In which city is the famous monument 'Charminar' located?", answer: "Hyderabad" },
        { question: "Which Indian state has the highest literacy rate?", answer: "Kerala" },
        { question: "Which river disappears into the sands of the Thar Desert?", answer: "Luni River" },
        { question: "Where is the high-altitude plateau region of India known as Ladakh?", answer: "Jammu and Kashmir / Ladakh UT" },
        { question: "Which ocean is named after India?", answer: "Indian Ocean" },
        { question: "What is the name of the oldest mountain range in India?", answer: "Aravalli Range" },
        { question: "Which city is known as the 'Pink City' of India?", answer: "Jaipur" },
        { question: "Which classical dance form originated in Tamil Nadu?", answer: "Bharatanatyam" },
        { question: "Which classical dance form originated in Kerala?", answer: "Kathakali" },
        { question: "When is Independence Day celebrated in India?", answer: "15th August" },
        { question: "When is Republic Day celebrated in India?", answer: "26th January" },
        { question: "Which metal was first used by citizens of Indus Valley Civilization?", answer: "Copper" },
        { question: "Who is known as the 'Father of the Indian Constitution'?", answer: "Dr. B.R. Ambedkar" },
        { question: "Which pass connects Srinagar to Leh?", answer: "Zoji La Pass" },
        { question: "Which sanctuary is famous for protecting the One-horned Rhinoceros?", answer: "Kaziranga National Park" },
        { question: "Which city is located at the confluence of Ganga, Yamuna, and Saraswati?", answer: "Prayagraj (Allahabad)" },
        { question: "Which island group of India is located in the Arabian Sea?", answer: "Lakshadweep Islands" },
        { question: "Which island group of India is located in the Bay of Bengal?", answer: "Andaman and Nicobar Islands" },
        { question: "What is the national tree of India?", answer: "Banyan Tree" },
        { question: "What is the national fruit of India?", answer: "Mango" },
        { question: "Which empire built the sun temple at Konark?", answer: "Eastern Ganga Dynasty" },
        { question: "Who was the first Indian woman to win an Olympic medal?", answer: "Karnam Malleswari" },
        { question: "Which lake is the largest freshwater lake in India?", answer: "Wular Lake" },
        { question: "Which dam is built across the Mahanadi river and is one of the longest in the world?", answer: "Hirakud Dam" },
        { question: "Which state is known as the 'Land of Five Rivers'?", answer: "Punjab" },
        { question: "What is the name of the active volcano belonging to India in the Andaman Sea?", answer: "Barren Island" }
    ],
    set2: [
        { question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
        { question: "What is the hardest natural substance on Earth?", answer: "Diamond" },
        { question: "Which continent is the Sahara Desert located on?", answer: "Africa" },
        { question: "What chemical element has the symbol 'O'?", answer: "Oxygen" },
        { question: "What is the smallest prime number?", answer: "2" },
        { question: "Which planet is known as the Red Planet?", answer: "Mars" },
        { question: "What is the largest ocean on Earth?", answer: "Pacific Ocean" },
        { question: "How many elements are currently verified on the periodic table?", answer: "118" },
        { question: "Which layer of the Earth is primarily made of liquid iron and nickel?", answer: "Outer Core" },
        { question: "What is the capital city of France?", answer: "Paris" },
        { question: "Which country is known as the Land of the Rising Sun?", answer: "Japan" },
        { question: "What is the longest river in the world?", answer: "Nile River" },
        { question: "Which is the largest country in the world by land area?", answer: "Russia" },
        { question: "Which is the smallest country in the world by land area?", answer: "Vatican City" },
        { question: "What is the capital city of Australia?", answer: "Canberra" },
        { question: "Which deep trench is the lowest point on the Earth's surface?", answer: "Mariana Trench" },
        { question: "What is the tallest mountain above sea level on Earth?", answer: "Mount Everest" },
        { question: "Which country gifted the Statue of Liberty to the United States?", answer: "France" },
        { question: "What gas makes up the majority of Earth's atmosphere?", answer: "Nitrogen" },
        { question: "Which currency is used across the majority of European Union nations?", answer: "Euro" },
        { question: "What is the chemical formula for water?", answer: "H2O" },
        { question: "Which imaginary line divides the Earth into Northern and Southern Hemispheres?", answer: "Equator" },
        { question: "What is the largest land mammal alive today?", answer: "African Elephant" },
        { question: "What is the largest animal to ever exist on Earth?", answer: "Blue Whale" },
        { question: "Which ancient civilization constructed the Great Pyramids of Giza?", answer: "Egyptians" },
        { question: "Which empire built the Colosseum in Rome?", answer: "Roman Empire" },
        { question: "Who discovered penicillin in 1928?", answer: "Alexander Fleming" },
        { question: "What is the speed of light in a vacuum approximately?", answer: "300,000 km/s" },
        { question: "Which gas do plants absorb from the atmosphere for photosynthesis?", answer: "Carbon Dioxide" },
        { question: "What is the primary instrument used to measure earthquakes?", answer: "Seismograph" },
        { question: "Which country is both a country and a continent?", answer: "Australia" },
        { question: "What is the capital city of Canada?", answer: "Ottawa" },
        { question: "Which organ filter blood and produces urine in the human body?", answer: "Kidneys" },
        { question: "What is the main function of red blood cells?", answer: "Carry Oxygen" },
        { question: "Who developed the theory of relativity?", answer: "Albert Einstein" },
        { question: "Which frozen continent is located at the South Pole?", answer: "Antarctica" },
        { question: "Which canal connects the Mediterranean Sea to the Red Sea?", answer: "Suez Canal" },
        { question: "Which canal connects the Atlantic Ocean to the Pacific Ocean?", answer: "Panama Canal" },
        { question: "What is the capital city of Brazil?", answer: "Brasilia" },
        { question: "Which country has the largest population in the world?", answer: "India" },
        { question: "What is the name of the closest star system to our Sun?", answer: "Alpha Centauri" },
        { question: "How many bones are there in an adult human body?", answer: "206" },
        { question: "Which structural system keeps track of genetic building instructions in cells?", answer: "DNA" },
        { force: "What force pulls objects toward the center of the Earth?", answer: "Gravity" },
        { question: "Which is the smallest continent by land area?", answer: "Australia" },
        { question: "Which temperature scale sets absolute zero at 0 degrees?", answer: "Kelvin" },
        { question: "What is the freezing point of water on the Celsius scale?", answer: "0°C" },
        { question: "Which major organ pumps blood throughout the human body?", answer: "Heart" },
        { question: "Who is credited with inventing the telephone?", answer: "Alexander Graham Bell" },
        { question: "Which celestial body orbits the Earth?", answer: "The Moon" },
]
};
